/*
#__________________________________________________________#
#Generated by:                                NITIN KUMAR  #
#                                             ASET,BIJWASEN#
#__________________________________________________________#
*/

#include <bits/stdc++.h>
using namespace std;

#define NL putchar_unlocked('\n')
#define endl '\n'
//LOOPS
#define rep(i, a, b) for(int i = a; i < (b); ++i)
#define all(x) x.begin(), x.end()
#define sz(x) (int)(x).size()
//HCF LCM
#define gcd(x,y) __gcd(x, y)
#define lcm(x,y) x*y/GCD(x,y)
//DATATYPE SHORT HAND
#define ll long long
#define ull unsigned ll
//CONSTANT
#define mod 1000000007
//VECTOR AND PAIR
#define eb emplace_back
#define vi vector <int>
#define si set<int>
#define vl vector <ll>
#define vs vector <string>
#define pii pair<int,int>
//DEBUG FUNCTION
#define debug(var) printf(#var":%d",var)
	    //int myVar=100;
	    //__debug(myVar);

#define gchu(c) (c)=getchar_unlocked()
#define pchu(c) putchar_unlocked(c)
//MAX OR MIN,ABS
#define ABS(a) ((a) < 0 ? -(a) : (a))
#define max(i, j) (((i) > (j)) ? i : j)
#define min(i, j) (((i) < (j)) ? i : j)
//cout << "The maximum is " << MAX(a, b) << endl;
#define sz(x) (int)(x).size()
/////////////////////////////////////////////////////////////////////typedef complex<Real> P;
#define B begin()
#define E end()
#define UB upper_bound
#define all(x) (x).begin(),(x).end()
//LOOPS
//handels all data types,even pointers
#define foreach(i,t) for (__typeof(t.begin()) i=t.begin(); i!=t.end(); i++)
//pointer other than int data type is not possible,and can itterate only max range of unsized int
#define FOR(i,a,b) for(size_t (i)=(a);(i)<=(b);++i)
#define FOR_(i,a,b) for(size_t (i)=(a); (i)>=(b);--i)
#define REP(i,n) FOR(i,0,n)
#define REPD_(i,n) FOR_(i,n,0)
#define trav(a, x) for (auto& a : x)
////USE:{ trav(x, v) cout << x << ' '; cout << endl; }
//LOOPS
#define fast cin.sync_with_stdio(0); cin.tie(0);\
	         cin.exceptions(cin.failbit)
#define ret return 0
#define gnum int num;\
    scanf("%d",&num)
#define pnum  printf("%d",num)
#define gstr char str[100];\
        scanf("%s",str)
#define pstr printf("%s",str)
